pipeline {
    agent any
    options {
        timeout(time: 30, unit: 'MINUTES')
    }
    environment {
        scannerHome = tool 'SonarQube'
    }
    stages {
        stage('Checkout repository') {
            steps {
                echo "Entering 'Checkout repository' stage"
                checkout scm
                echo "Completed 'Checkout repository' stage"
            }
        }

        stage('Check Current Directory') {
            steps {
                sh "ls -la"
            }
        }

        stage('OWASP Dependency-Check Vulnerabilities') {
            steps {
                dependencyCheck additionalArguments: '''
                            -o './'
                            -s '../web'
                            -f 'ALL' 
                            --prettyPrint''', odcInstallation: 'OWASP Dependency-Check Vulnerabilities'

                dependencyCheckPublisher pattern: 'dependency-check-report.xml'
            }
        }

        stage('Code Quality Check via SonarQube') {
            steps {
                script {
                    def sonarScannerHome = tool 'SonarQube';
                    env.PATH = "${sonarScannerHome}/bin:${env.PATH}"

                    withSonarQubeEnv('SonarQube') {
                        sh """
                        sonar-scanner \
                        -Dsonar.projectKey=OWASP \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=http://sonarqube:9000 \
                        -Dsonar.login=sqp_7f6cbe44862d8384e3dbb716bcc2ad7105805ccd
                        """
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    sh "./web/test/test.py"
                }
            }
        }

        // stage('Run Tests') {
        //     steps {
        //         script {
        //             sh "pwd"  // Print current working directory
        //             sh "ls -la"  // List files in the current directory
        //             sh "chmod +x ./setup-jenkins/test.sh"
        //             sh "./setup-jenkins/test.sh"
        //         }
        //     }
        // }

        // stage('Build, start docker and kill images') {
        //     steps {
        //         sh "dockerd &"
        //         sh "docker --version"
        //         sh "docker-compose -f setup-jenkins/docker-compose.yml down"
        //         sh "docker-compose -f setup-jenkins/docker-compose.yml build"
        //         sh "docker-compose -f setup-jenkins/docker-compose.yml up -d"
        //         sh "docker ps"
        //         sh "docker-compose -f setup-jenkins/docker-compose.yml down"
        //     }
        // }
    }
}
